### ISSUE TITLE
Unhandled rejection after adding like 20 bots

### ISSUE THREAD

**Issue by KCtheDev** [tthomxs/kahoot-spammer#1]
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

I have no Idea how to fix this error
![image](https://user-images.githubusercontent.com/78183152/118872621-9b4fb300-b89d-11eb-91ab-599afee4c591.png)

**Comment by tthomxs** [comment]
this is because of promises, learn about them here https://www.javascripttutorial.net/es6/javascript-promises/
